//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_Product
    {
        public EC_Product()
        {
            this.EC_Command = new HashSet<EC_Command>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public string descriptionProduct { get; set; }
        public string imageProduct { get; set; }
        public int price { get; set; }
    
        public virtual ICollection<EC_Command> EC_Command { get; set; }
    }
}
