//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_User
    {
        public EC_User()
        {
            this.EC_Command = new HashSet<EC_Command>();
        }
    
        public string loginUser { get; set; }
        public string mpUser { get; set; }
        public string C_Type { get; set; }
    
        public virtual ICollection<EC_Command> EC_Command { get; set; }
    }
}
